baseurl = "https://blog.shymega.org.uk/"
languageCode = "en-gb"
title = "new Blog().build()"
theme = "temple"

[params]
  # Enables syntax highlighting
  highlight = true 
  hjslangs = ["go", "elixir", "clojure"]
  topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "dom rodriguez (shymega)"
  github = "shymega"
  email = "shymega@shymega.org.uk"
  twitter = "shymega_"
